finalmovie/Final_MovieProject/urls.py
from django.contrib import admin
from django.urls import path,include
from Final_MovieProject import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('MovieApp.urls')),
    path('search/',include('search_app.urls')),
    path('credentials/',include('credentials.urls')),
    path('profileapp/',include('profileapp.urls')),
]+static(settings.STATIC_ROOT,document_root=settings.STATIC_ROOT)\
              +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

finalmovie/MovieApp/urls.py
from django.urls import path
from MovieApp import views
app_name='Movie_App'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('categories/',views.category_detail,name='category_list'),
    path('category/<int:category_id>/',views.detail_category,name='detail_category')
]

finalmovie/credentials/urls.py
from django.urls import path
from credentials import views
app_name='credentialapp'

urlpatterns=[
     path('register',views.register,name='register'),
     path('login',views.login,name='login'),
     path('logout',views.logout,name='logout'),
]

finalmovie/profileapp/urls.py
from django.urls import path
from profileapp import views
app_name='profileapp'

urlpatterns=[

     path('profile',views.profile,name='profile'),
     path('edit_profile/<int:id>/',views.edit_profile,name='edit_profile'),
]

finalmovie/search_app/urls.py
from django.urls import path
from search_app import views

app_name='search_app'

urlpatterns=[
    path('',views.searchReasult,name='searchResult')
]

finalmovie/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title" placeholder="enter your movie title">
    <input type="text" name="description" placeholder="enter description">
    <input type="date" name="release_date" placeholder="enter release date">
    <input type="text" name="actors" placeholder="enter Actors">
    <input type="url" name="poster" placeholder="Enter url poster">
    <input type="url" name="youtube_trailer_link" placeholder="trailer link">
    <input type="file" name="image" >
    <label for="category">Category:</label>
        <select name="category" required>
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select><br>
    <input type="submit">
</form>



{% endblock %}

finalmovie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>my index page</title>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand">Online Movie Store</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a  href="{% url 'Movie_App:add_movie' %}" class="btn btn-primary">Add Movie</a>
        </li>


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'Movie_App:category_list' %}">All Categories</a></li>
          </ul>
        <li class="nav-item">
          <a  href="{% url 'credentialapp:logout' %}" class="btn btn-primary">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Movie_App:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a  href="{% url 'profileapp:profile' %}" class="btn btn-primary">view Profile</a>
        </li>

      </ul>
       <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
                {% csrf_token %}
         <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
         <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
       </form>

    </div>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

finalmovie/templates/category.html
{% extends 'base.html' %}
{% block body %}
<a href="{% url 'Movie_App:index' %}" class="btn btn-info">All Movies</a><br>

<div class="container mt-5">
    <div class="row">
        {% for i in category_list %}
        <br><div class="card mb-3" style="max-width: 500px;">
  <div class="row g-0">
    <div class="col-md-4">

    <div class="col-md-8">
      <div class="card-body">
          <a href="{% url  'Movie_App:detail_category' i.id %}" class="btn btn-info">{{i.name}}</a>

      </div>
    </div>
  </div>
</div>
        {%  endfor %}


</div>
</div>

{% endblock %}

finalmovie/templates/category_movies.html
{% extends 'base.html' %}
{% block body %}

  <h1>Movies in {{ category.name }}</h1>

  {% if movies %}
    <ul>
      {% for movie in movies %}
        <li>{{ movie.title }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No movies in this category.</p>
  {% endif %}

{% endblock %}

finalmovie/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form  method="post">

  {% csrf_token %}

  <h2>Are you sure?</h2>
  <input type="submit">

</form>
{% endblock %}

finalmovie/templates/detail.html
{% extends 'base.html' %}
{% block body %}


<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.image.url}}"width="400" height="400">
        </div>
    <div class="col-md-6">
        <h5>Movie Title:{{movie.title}}</h5>
        <p>Movie Description:{{movie.description}}</p>
          <p>Movie Actors:{{movie.actors}}</p>
         <h5 class="card-link">Youtube_link:{{movie.youtube_trailer_link}}</h5>
        <a class="btn btn-warning" href="{% url 'Movie_App:update' movie.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'Movie_App:delete' movie.id %}">delete</a>
    </div>


    </div>
</div>
{% endblock %}

finalmovie/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<style>
  form{
    text-align: center;
  }
</style>
<form  method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock %}

finalmovie/templates/edit_profile.html
{% extends 'base.html' %}
{% block body %}
<style>
  form{
    text-align: center;
  }
</style>
<form  method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock %}

finalmovie/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container mt-3">
    <div class="row">
        <div class="row row-cols-1 row-cols-md-3 g-4 mt-3">
            {% for i in movie_list %}

            <div class="col">
                <div class="card h-100">
                    <img src="{{i.image.url}}" class="card-img-top" alt="">
                    <div class="card-body">
                        <h5 class="card-title" style="text-align: center;">{{i.title}}</h5>
                        <p class="card-text" style="text-align: center;">{{i.description}}</p>
                        <h5 class="card-title" style="text-align: center;">Actors:{{i.actors}}</h5>
                    </div>

                    <div class="card-body" style="text-align: center;">
                        <a href="{% url  'Movie_App:detail' i.id %}" class="btn btn-info">View Details</a>
                    </div>
                </div>
            </div>
                {% endfor %}
        </div>
    </div>
    {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

</div>

{% endblock %}

finalmovie/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login page</title>
    <style>
     body{
            text-align: center;

            margin-top: 50px;
            color: pink;
            background-image:url('https://images.pexels.com/photos/3991970/pexels-photo-3991970.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')

        }
        input{
            padding: 5px;
        }
     </style>
</head>
<body>
<h2 style=" text-align: center;">Login here</h2>
<form style="text-align:center;" action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username"><br>
    <br><input type="password" name="password" placeholder="Enter password"><br>
    <br><input type="submit">

</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}

</body>
</html>

finalmovie/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      Online Movie Store
    </a>
  </div>
  </div>
</nav>
<br>
 <!--<button class= type="submit">Add Movie</button>-->
<br><div style="text-align: center;"><br>

    <a class="btn btn-outline-dark" aria-current="page" href="{% url 'credentialapp:login' %}">Login to Join</a><br>

    <br><div style="text-align: center;">You don't have A Valid Account? SignUp!</div>
          <br>
          <br><div style="text-align: center;"><br>
          <a class="btn btn-outline-dark" aria-current="page" href="{% url 'credentialapp:register' %}">Create An Account</a>

      </div>
</body>
</html>

</body>
</html>

finalmovie/templates/profile.html
{% extends 'base.html' %}
{% block body %}


<div class="container mt-4">
  <div class="row">
      {% for i in profile %}
    <div class="col-md-6">
      {% if i.profile_pic %}
        <img src="{{ i.profile_pic.url }}" width="400" height="400">
      {% endif %}
    </div>
    <div class="col-md-6">
      <h5>{{ i.user.username }}</h5>
      <p>{{ i.bio }}</p>
      {% if i.date_of_birth %}
        <p>{{ i.date_of_birth }}</p>
      {% endif %}
      {% if i.location %}
        <h5 class="card-text">{{ i.location }}</h5>
      {% endif %}
    </div>
    <br>
    <a class="btn btn-danger" href="{% url 'profileapp:edit_profile' i.id %}">Update</a>

  </div>

{%endfor%}
</div>
{% endblock %}

finalmovie/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <style>
        body{
            text-align: center;

            margin-top: 50px;
            background-image:url('https://images.pexels.com/photos/3991970/pexels-photo-3991970.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')

        }
        input{
            padding: 5px;
        }

    </style>

</head>
<body>

<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username"><br>

    <br><input type="text" name="first_name" placeholder="Enter your firstname"><br>
    <br> <input type="text" name="last_name" placeholder="Enter your lastname"><br>
    <br><input type="email" name="Email" placeholder="enter email"><br>
    <br><input type="password" name="Password" placeholder="Enter password"><br>
    <br><input type="password" name="password" placeholder="Confirm your Password"><br>
    <br><input type="submit">
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}

</body>
</html>

finalmovie/templates/search.html
{% extends 'base.html' %}
{% block body %}

<div>
    <p class="text-center my_search_text"> You Have Searched For : <b>"{{search_query}}"</b> </p>
</div>

    {% if movies %}
  <div class="row">
 {% for movie in category_list %}
    <a href="{% url  'Movie_App:detail_category' i.id %}" class="btn btn-info">{{movie.name}}</a>
{%endfor%}
            {% for movie in movies %}

                 <div class="row">
                    <div class="col-md-6">
                        <img src="{{movie.image.url}}"width="300" height="300"></div>
                     <div class="col-md-6">
                        <h2> {{movie.title}}</h2>
                        <h6>{{movie.description}}</h6>
                         <h5>{{movie.category}}</h5>
                        <h5>{{movie.actors}}</h5>
                        <h5>{{movie.youtube_trailer_link}}</h5>
                     </div>
                 </div>

            {% endfor %}

    {% else %}
        <p>No movies found.</p>
    {% endif %}

{% endblock %}